/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as VTokenRouteImport } from './routes/v.$token'
import { Route as NTokenRouteImport } from './routes/n.$token'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated.vendas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedRelatorioSetorRouteImport } from './routes/_authenticated.relatorio-setor'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated.notificacoes'
import { Route as AuthenticatedMinhasParcelasRouteImport } from './routes/_authenticated.minhas-parcelas'
import { Route as AuthenticatedJuridicoRouteImport } from './routes/_authenticated.juridico'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated.importar'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated.fornecedores'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated.contratos'
import { Route as AuthenticatedContasAPagarRouteImport } from './routes/_authenticated.contas-a-pagar'
import { Route as AuthenticatedComissoesRouteImport } from './routes/_authenticated.comissoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated.clientes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAcordosRouteImport } from './routes/_authenticated.acordos'
import { Route as AuthenticatedContratosIndexRouteImport } from './routes/_authenticated.contratos.index'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated.contratos.$id'
import { Route as ApiPublicSalesTokenRouteImport } from './routes/api/public/sales.$token'
import { Route as ApiPublicNotificationsTokenRouteImport } from './routes/api/public/notifications.$token'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'
import { Route as ApiPublicAgreementsTokenRouteImport } from './routes/api/public/agreements.$token'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const NTokenRoute = NTokenRouteImport.update({
  id: '/n/$token',
  path: '/n/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatorioSetorRoute =
  AuthenticatedRelatorioSetorRouteImport.update({
    id: '/relatorio-setor',
    path: '/relatorio-setor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhasParcelasRoute =
  AuthenticatedMinhasParcelasRouteImport.update({
    id: '/minhas-parcelas',
    path: '/minhas-parcelas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJuridicoRoute = AuthenticatedJuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContasAPagarRoute =
  AuthenticatedContasAPagarRouteImport.update({
    id: '/contas-a-pagar',
    path: '/contas-a-pagar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComissoesRoute = AuthenticatedComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcordosRoute = AuthenticatedAcordosRouteImport.update({
  id: '/acordos',
  path: '/acordos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContratosIndexRoute =
  AuthenticatedContratosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const ApiPublicSalesTokenRoute = ApiPublicSalesTokenRouteImport.update({
  id: '/api/public/sales/$token',
  path: '/api/public/sales/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsTokenRoute =
  ApiPublicNotificationsTokenRouteImport.update({
    id: '/api/public/notifications/$token',
    path: '/api/public/notifications/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgreementsTokenRoute =
  ApiPublicAgreementsTokenRouteImport.update({
    id: '/api/public/agreements/$token',
    path: '/api/public/agreements/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/trust': typeof TrustRoute
  '/acordos': typeof AuthenticatedAcordosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/contas-a-pagar': typeof AuthenticatedContasAPagarRoute
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/juridico': typeof AuthenticatedJuridicoRoute
  '/minhas-parcelas': typeof AuthenticatedMinhasParcelasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/relatorio-setor': typeof AuthenticatedRelatorioSetorRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/a/$token': typeof ATokenRoute
  '/n/$token': typeof NTokenRoute
  '/v/$token': typeof VTokenRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/contratos/': typeof AuthenticatedContratosIndexRoute
  '/api/public/agreements/$token': typeof ApiPublicAgreementsTokenRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/notifications/$token': typeof ApiPublicNotificationsTokenRoute
  '/api/public/sales/$token': typeof ApiPublicSalesTokenRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/trust': typeof TrustRoute
  '/acordos': typeof AuthenticatedAcordosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comissoes': typeof AuthenticatedComissoesRoute
  '/contas-a-pagar': typeof AuthenticatedContasAPagarRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/juridico': typeof AuthenticatedJuridicoRoute
  '/minhas-parcelas': typeof AuthenticatedMinhasParcelasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/relatorio-setor': typeof AuthenticatedRelatorioSetorRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/a/$token': typeof ATokenRoute
  '/n/$token': typeof NTokenRoute
  '/v/$token': typeof VTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/contratos': typeof AuthenticatedContratosIndexRoute
  '/api/public/agreements/$token': typeof ApiPublicAgreementsTokenRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/notifications/$token': typeof ApiPublicNotificationsTokenRoute
  '/api/public/sales/$token': typeof ApiPublicSalesTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/trust': typeof TrustRoute
  '/_authenticated/acordos': typeof AuthenticatedAcordosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comissoes': typeof AuthenticatedComissoesRoute
  '/_authenticated/contas-a-pagar': typeof AuthenticatedContasAPagarRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/juridico': typeof AuthenticatedJuridicoRoute
  '/_authenticated/minhas-parcelas': typeof AuthenticatedMinhasParcelasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/relatorio-setor': typeof AuthenticatedRelatorioSetorRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/a/$token': typeof ATokenRoute
  '/n/$token': typeof NTokenRoute
  '/v/$token': typeof VTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/_authenticated/contratos/': typeof AuthenticatedContratosIndexRoute
  '/api/public/agreements/$token': typeof ApiPublicAgreementsTokenRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
  '/api/public/notifications/$token': typeof ApiPublicNotificationsTokenRoute
  '/api/public/sales/$token': typeof ApiPublicSalesTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/trust'
    | '/acordos'
    | '/admin'
    | '/clientes'
    | '/comissoes'
    | '/contas-a-pagar'
    | '/contratos'
    | '/fornecedores'
    | '/importar'
    | '/juridico'
    | '/minhas-parcelas'
    | '/notificacoes'
    | '/relatorio-setor'
    | '/relatorios'
    | '/vendas'
    | '/a/$token'
    | '/n/$token'
    | '/v/$token'
    | '/contratos/$id'
    | '/api/public/asaas-webhook'
    | '/contratos/'
    | '/api/public/agreements/$token'
    | '/api/public/hooks/reminders'
    | '/api/public/notifications/$token'
    | '/api/public/sales/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/trust'
    | '/acordos'
    | '/admin'
    | '/clientes'
    | '/comissoes'
    | '/contas-a-pagar'
    | '/fornecedores'
    | '/importar'
    | '/juridico'
    | '/minhas-parcelas'
    | '/notificacoes'
    | '/relatorio-setor'
    | '/relatorios'
    | '/vendas'
    | '/a/$token'
    | '/n/$token'
    | '/v/$token'
    | '/'
    | '/contratos/$id'
    | '/api/public/asaas-webhook'
    | '/contratos'
    | '/api/public/agreements/$token'
    | '/api/public/hooks/reminders'
    | '/api/public/notifications/$token'
    | '/api/public/sales/$token'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/trust'
    | '/_authenticated/acordos'
    | '/_authenticated/admin'
    | '/_authenticated/clientes'
    | '/_authenticated/comissoes'
    | '/_authenticated/contas-a-pagar'
    | '/_authenticated/contratos'
    | '/_authenticated/fornecedores'
    | '/_authenticated/importar'
    | '/_authenticated/juridico'
    | '/_authenticated/minhas-parcelas'
    | '/_authenticated/notificacoes'
    | '/_authenticated/relatorio-setor'
    | '/_authenticated/relatorios'
    | '/_authenticated/vendas'
    | '/a/$token'
    | '/n/$token'
    | '/v/$token'
    | '/_authenticated/'
    | '/_authenticated/contratos/$id'
    | '/api/public/asaas-webhook'
    | '/_authenticated/contratos/'
    | '/api/public/agreements/$token'
    | '/api/public/hooks/reminders'
    | '/api/public/notifications/$token'
    | '/api/public/sales/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrustRoute: typeof TrustRoute
  ATokenRoute: typeof ATokenRoute
  NTokenRoute: typeof NTokenRoute
  VTokenRoute: typeof VTokenRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicAgreementsTokenRoute: typeof ApiPublicAgreementsTokenRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
  ApiPublicNotificationsTokenRoute: typeof ApiPublicNotificationsTokenRoute
  ApiPublicSalesTokenRoute: typeof ApiPublicSalesTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$token': {
      id: '/n/$token'
      path: '/n/$token'
      fullPath: '/n/$token'
      preLoaderRoute: typeof NTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorio-setor': {
      id: '/_authenticated/relatorio-setor'
      path: '/relatorio-setor'
      fullPath: '/relatorio-setor'
      preLoaderRoute: typeof AuthenticatedRelatorioSetorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minhas-parcelas': {
      id: '/_authenticated/minhas-parcelas'
      path: '/minhas-parcelas'
      fullPath: '/minhas-parcelas'
      preLoaderRoute: typeof AuthenticatedMinhasParcelasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/juridico': {
      id: '/_authenticated/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof AuthenticatedJuridicoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contas-a-pagar': {
      id: '/_authenticated/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof AuthenticatedContasAPagarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comissoes': {
      id: '/_authenticated/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof AuthenticatedComissoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acordos': {
      id: '/_authenticated/acordos'
      path: '/acordos'
      fullPath: '/acordos'
      preLoaderRoute: typeof AuthenticatedAcordosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos/': {
      id: '/_authenticated/contratos/'
      path: '/'
      fullPath: '/contratos/'
      preLoaderRoute: typeof AuthenticatedContratosIndexRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/api/public/sales/$token': {
      id: '/api/public/sales/$token'
      path: '/api/public/sales/$token'
      fullPath: '/api/public/sales/$token'
      preLoaderRoute: typeof ApiPublicSalesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications/$token': {
      id: '/api/public/notifications/$token'
      path: '/api/public/notifications/$token'
      fullPath: '/api/public/notifications/$token'
      preLoaderRoute: typeof ApiPublicNotificationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agreements/$token': {
      id: '/api/public/agreements/$token'
      path: '/api/public/agreements/$token'
      fullPath: '/api/public/agreements/$token'
      preLoaderRoute: typeof ApiPublicAgreementsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedContratosRouteChildren {
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRoute
  AuthenticatedContratosIndexRoute: typeof AuthenticatedContratosIndexRoute
}

const AuthenticatedContratosRouteChildren: AuthenticatedContratosRouteChildren =
  {
    AuthenticatedContratosIdRoute: AuthenticatedContratosIdRoute,
    AuthenticatedContratosIndexRoute: AuthenticatedContratosIndexRoute,
  }

const AuthenticatedContratosRouteWithChildren =
  AuthenticatedContratosRoute._addFileChildren(
    AuthenticatedContratosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAcordosRoute: typeof AuthenticatedAcordosRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComissoesRoute: typeof AuthenticatedComissoesRoute
  AuthenticatedContasAPagarRoute: typeof AuthenticatedContasAPagarRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRouteWithChildren
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedJuridicoRoute: typeof AuthenticatedJuridicoRoute
  AuthenticatedMinhasParcelasRoute: typeof AuthenticatedMinhasParcelasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedRelatorioSetorRoute: typeof AuthenticatedRelatorioSetorRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcordosRoute: AuthenticatedAcordosRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComissoesRoute: AuthenticatedComissoesRoute,
  AuthenticatedContasAPagarRoute: AuthenticatedContasAPagarRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRouteWithChildren,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedJuridicoRoute: AuthenticatedJuridicoRoute,
  AuthenticatedMinhasParcelasRoute: AuthenticatedMinhasParcelasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedRelatorioSetorRoute: AuthenticatedRelatorioSetorRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  TrustRoute: TrustRoute,
  ATokenRoute: ATokenRoute,
  NTokenRoute: NTokenRoute,
  VTokenRoute: VTokenRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicAgreementsTokenRoute: ApiPublicAgreementsTokenRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
  ApiPublicNotificationsTokenRoute: ApiPublicNotificationsTokenRoute,
  ApiPublicSalesTokenRoute: ApiPublicSalesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
