INSERT INTO public.notification_templates (name, subject, body)
SELECT * FROM (VALUES
('Notificação Extrajudicial de Cobrança',
 'Notificação Extrajudicial — Contrato {{contrato_numero}}',
 E'NOTIFICAÇÃO EXTRAJUDICIAL DE COBRANÇA\n\nNotificante: MML ASSESSORIA E COBRANÇA\nNotificado(a): {{cliente_nome}}\nCPF/CNPJ: {{cliente_documento}}\nContrato nº: {{contrato_numero}} — {{contrato_descricao}}\nData: {{data_hoje}}\n\nPrezado(a) Sr.(a) {{cliente_nome}},\n\nNa qualidade de representante do credor, servimo-nos da presente NOTIFICAÇÃO EXTRAJUDICIAL para comunicar que consta em nossos registros débito vencido e não pago referente ao contrato acima identificado.\n\nDEMONSTRATIVO DO DÉBITO\nParcelas em atraso: {{parcelas_atrasadas}}\nValor original: {{valor_original}} ({{valor_original_extenso}})\nMulta contratual (2%): {{multa}}\nJuros de mora (1% a.m.): {{juros}}\nVALOR ATUALIZADO: {{valor_atualizado}} ({{valor_atualizado_extenso}})\n\nDETALHAMENTO DAS PARCELAS\n{{tabela_parcelas}}\n\nCLÁUSULAS E ADVERTÊNCIAS\n1. Fica o(a) notificado(a) CONSTITUÍDO(A) EM MORA, nos termos do art. 397 do Código Civil.\n2. O pagamento deverá ocorrer no prazo de 05 (cinco) dias úteis contados do recebimento desta.\n3. Decorrido o prazo sem quitação ou acordo, serão adotadas as medidas cabíveis, incluindo inscrição do débito nos órgãos de proteção ao crédito (SPC/SERASA), protesto do título e execução judicial, com acréscimo de custas processuais e honorários advocatícios.\n4. Caso o pagamento já tenha sido efetuado, favor desconsiderar esta notificação e encaminhar o comprovante.\n\nColocamo-nos à disposição para negociação e parcelamento do débito.\n\nAtenciosamente,\nDepartamento Jurídico\nMML Assessoria e Cobrança'),
('Aviso de Vencimento (Amigável)',
 'Aviso de parcelas em aberto — Contrato {{contrato_numero}}',
 E'Prezado(a) {{cliente_nome}},\n\nIdentificamos em nossos registros parcelas em aberto referentes ao contrato nº {{contrato_numero}} ({{contrato_descricao}}).\n\nResumo em {{data_hoje}}:\nParcelas em atraso: {{parcelas_atrasadas}}\nValor original: {{valor_original}}\nMulta e juros: {{multa}} + {{juros}}\nTotal atualizado: {{valor_atualizado}} ({{valor_atualizado_extenso}})\n\nParcelas:\n{{tabela_parcelas}}\n\nSolicitamos a regularização o quanto antes para evitar encargos adicionais e restrições cadastrais. Havendo interesse, podemos avaliar condições especiais de parcelamento.\n\nEm caso de pagamento já realizado, desconsidere este aviso.\n\nAtenciosamente,\nMML Assessoria e Cobrança\nContato: {{cliente_telefone}}'),
('Última Oportunidade Antes do Protesto',
 'ÚLTIMO AVISO — Contrato {{contrato_numero}}',
 E'ÚLTIMO AVISO ANTES DE PROTESTO E AÇÃO JUDICIAL\n\nNotificado(a): {{cliente_nome}} — CPF/CNPJ {{cliente_documento}}\nContrato nº {{contrato_numero}} — {{contrato_descricao}}\nData: {{data_hoje}}\n\nApesar das tentativas anteriores de contato, permanece em aberto o débito abaixo:\n\nParcelas vencidas: {{parcelas_atrasadas}}\nValor atualizado: {{valor_atualizado}} ({{valor_atualizado_extenso}})\n\n{{tabela_parcelas}}\n\nConcedemos o prazo improrrogável de 48 (quarenta e oito) horas para quitação ou formalização de acordo. Findo o prazo, o título será encaminhado a PROTESTO e o débito será objeto de AÇÃO JUDICIAL DE EXECUÇÃO, com acréscimo de custas e honorários advocatícios de 20%.\n\nPara negociar, entre em contato imediatamente com o Departamento Jurídico.\n\nMML Assessoria e Cobrança')
) AS t(name, subject, body)
WHERE NOT EXISTS (SELECT 1 FROM public.notification_templates);